# Generated by Django 2.1 on 2018-12-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ReadDetail',
        ),
    ]
